/**
 * Email service — Resend seam.
 *
 * In the frontend prototype this is a MOCK: it renders the real HTML that a
 * Resend transactional email would contain and pushes it to the in-app outbox
 * so the demo can show the exact message a reporter receives. The integration
 * point is isolated here: to go live, POST to `${apiBase}/email/send` (your
 * backend), which calls Resend server-side with RESEND_API_KEY. The key must
 * NEVER live in the frontend bundle.
 */

export type EmailKind = 'case_created' | 'confirmation_added' | 'repair_verified';

export interface EmailMessage {
  id: string;
  kind: EmailKind;
  to: string;
  subject: string;
  /** Rendered HTML body (safe — generated by us, not user input). */
  html: string;
  /** Short plain-text summary for the outbox list. */
  preview: string;
  hazardId: string;
  createdAt: string;
  /** true once a real backend/Resend accepted it (always false in mock tier). */
  delivered: boolean;
}

const BRAND = {
  ink: '#0A0B0E',
  card: '#131519',
  line: '#25282E',
  text: '#F2F4F7',
  muted: '#8A909A',
  accent: '#5B84FF',
};

function shell(title: string, bodyHtml: string): string {
  return `<!doctype html><html><body style="margin:0;background:${BRAND.ink};font-family:Inter,Arial,sans-serif;color:${BRAND.text}">
  <div style="max-width:560px;margin:0 auto;padding:32px 20px">
    <div style="font-size:13px;letter-spacing:.14em;text-transform:uppercase;color:${BRAND.muted};font-weight:700">RoadDrive AI</div>
    <div style="margin-top:18px;background:${BRAND.card};border:1px solid ${BRAND.line};border-radius:14px;padding:24px">
      <h1 style="margin:0 0 12px;font-size:20px;line-height:1.3">${title}</h1>
      ${bodyHtml}
    </div>
    <p style="margin:18px 4px 0;font-size:11px;color:${BRAND.muted}">You are receiving this because you submitted a road hazard report. Faces and license plates are blurred before any evidence is stored.</p>
  </div>
</body></html>`;
}

const b = (t: string) => `<p style="margin:0 0 12px;font-size:14px;line-height:1.6;color:${BRAND.text}">${t}</p>`;
const muted = (t: string) => `<p style="margin:0;font-size:12px;line-height:1.6;color:${BRAND.muted}">${t}</p>`;
const pill = (t: string, color: string) =>
  `<span style="display:inline-block;padding:3px 10px;border-radius:999px;font-size:11px;font-weight:700;color:${color};border:1px solid ${color}55;background:${color}14">${t}</span>`;

export interface EmailContext {
  to: string;
  hazardId: string;
  hazardType: string;
  roadName: string;
  severity: string;
  confirmations?: number;
  caseNumber?: string;
  repairVerifiedBy?: number;
}

/** Builds the transactional email for a given event. Pure — no side effects. */
export function buildEmail(kind: EmailKind, ctx: EmailContext): Omit<EmailMessage, 'id' | 'createdAt' | 'delivered'> {
  switch (kind) {
    case 'case_created': {
      const subject = `New road hazard case filed — ${ctx.hazardId}`;
      const html = shell(
        'Your report created a new case',
        `${b(`Thank you — your report of <b>${ctx.hazardType}</b> on <b>${ctx.roadName}</b> was the first for this defect, so it has opened a new tracking case.`)}
         ${b(`<span style="color:${BRAND.accent};font-weight:700">${ctx.caseNumber ?? ctx.hazardId}</span> is now visible to the road authority.`)}
         <div style="margin:16px 0 4px">${pill(ctx.severity.toUpperCase() + ' SEVERITY', BRAND.accent)}</div>
         ${muted('You will be notified when the repair is verified on the road.')}`,
      );
      return { kind, to: ctx.to, subject, html, preview: `Case ${ctx.caseNumber ?? ctx.hazardId} filed for your report on ${ctx.roadName}.`, hazardId: ctx.hazardId };
    }
    case 'confirmation_added': {
      const subject = `Your report matched an existing hazard — ${ctx.hazardId}`;
      const html = shell(
        'Your report was added as a confirmation',
        `${b(`Your report of <b>${ctx.hazardType}</b> on <b>${ctx.roadName}</b> matched a hazard already being tracked (<b>${ctx.hazardId}</b>).`)}
         ${b(`Instead of filing a duplicate, your observation was counted as an <b>independent confirmation</b> — this raises the hazard's confidence and repair priority.`)}
         ${b(`This hazard now has <b style="color:${BRAND.accent}">${ctx.confirmations ?? 'several'}</b> confirmations.`)}
         ${muted('One pothole = one case. Your report still counts — it is not ignored.')}`,
      );
      return { kind, to: ctx.to, subject, html, preview: `Confirmation added to ${ctx.hazardId} (now ${ctx.confirmations ?? '—'} confirmations).`, hazardId: ctx.hazardId };
    }
    case 'repair_verified': {
      const subject = `Repair verified on ${ctx.roadName} — ${ctx.hazardId}`;
      const html = shell(
        'Good news — the road has been fixed',
        `${b(`The hazard you reported on <b>${ctx.roadName}</b> (<b>${ctx.hazardId}</b>) has been marked repaired and <b>independently verified</b>.`)}
         ${b(`${ctx.repairVerifiedBy ?? 'Multiple'} independent vehicle passes detected no defect.`)}
         <div style="margin:16px 0 4px">${pill('REPAIR VERIFIED', '#22C55E')}</div>
         ${muted('Thank you for helping keep the roads driveable.')}`,
      );
      return { kind, to: ctx.to, subject, html, preview: `Repair verified on ${ctx.roadName} — case ${ctx.hazardId}.`, hazardId: ctx.hazardId };
    }
  }
}

/**
 * Sends via Resend when a backend is configured; otherwise returns the mock
 * message for the in-app outbox. `VITE_EMAIL_API_BASE` points at your backend.
 */
export async function sendEmail(
  kind: EmailKind,
  ctx: EmailContext,
  makeId: () => string,
): Promise<EmailMessage> {
  const base = buildEmail(kind, ctx);
  const msg: EmailMessage = { ...base, id: makeId(), createdAt: new Date().toISOString(), delivered: false };

  const apiBase = (import.meta as any).env?.VITE_EMAIL_API_BASE as string | undefined;
  if (apiBase) {
    try {
      const res = await fetch(`${apiBase.replace(/\/$/, '')}/email/send`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ kind, to: ctx.to, hazardId: ctx.hazardId }),
      });
      if (res.ok) msg.delivered = true;
    } catch {
      /* keep as mock on failure — never throw into the UI */
    }
  }
  return msg;
}