import { X, Mail, CheckCircle2 } from 'lucide-react';
import type { EmailMessage } from '../../types';
import { timeAgo } from '../../utils/severity';

/**
 * Renders the exact transactional email a reporter receives (Resend seam).
 * The HTML body is generated by api/email.ts — this just frames it.
 */
export function EmailPreviewModal({ email, onClose }: { email: EmailMessage; onClose: () => void }) {
  return (
    <div
      className="fixed inset-0 z-40 flex items-end justify-center bg-black/60 sm:items-center"
      role="dialog"
      aria-modal="true"
      aria-label="Email preview"
      onClick={onClose}
    >
      <div
        className="flex max-h-[88vh] w-full max-w-lg flex-col overflow-hidden rounded-t-2xl border border-line bg-card shadow-raised sm:rounded-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        {/* mail client chrome */}
        <div className="flex items-center justify-between border-b border-line px-4 py-3">
          <div className="flex items-center gap-2">
            <Mail className="h-4 w-4 text-primary-400" aria-hidden />
            <span className="text-sm font-semibold text-ink">Email preview</span>
            {email.delivered ? (
              <span className="chip border-green-500/30 bg-green-500/10 text-green-300">Delivered</span>
            ) : (
              <span className="chip border-line bg-soft text-muted">Resend · mock</span>
            )}
          </div>
          <button className="text-muted hover:text-gray-200" aria-label="Close" onClick={onClose}>
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* headers */}
        <div className="space-y-1 border-b border-line px-4 py-3 text-xs">
          <div className="flex gap-2"><span className="w-14 text-muted">To</span><span className="text-ink-soft">{email.to}</span></div>
          <div className="flex gap-2"><span className="w-14 text-muted">From</span><span className="text-ink-soft">RoadDrive AI &lt;notifications@roaddrive.gov.in&gt;</span></div>
          <div className="flex gap-2"><span className="w-14 text-muted">Subject</span><span className="font-semibold text-ink">{email.subject}</span></div>
        </div>

        {/* rendered HTML body */}
        <div className="min-h-0 flex-1 overflow-auto bg-card" dangerouslySetInnerHTML={{ __html: email.html }} />

        <div className="flex items-center justify-between gap-2 border-t border-line px-4 py-2.5 text-[11px] text-muted">
          <span className="flex items-center gap-1.5">
            <CheckCircle2 className="h-3.5 w-3.5 text-green-400" aria-hidden /> Sent {timeAgo(email.createdAt)}
          </span>
          <span>Generated by api/email.ts · swap to live Resend via VITE_EMAIL_API_BASE</span>
        </div>
      </div>
    </div>
  );
}